/**
 * reportExporters.js — generic CSV / PDF builders driven by a
 * declarative column spec.
 *
 * Column shape:
 *   {
 *     key:       string,                  // machine id, used in spec
 *     label:     string,                  // header label
 *     width:     string?,                 // PDF column width (e.g. '25mm')
 *     getter:    (row, ctx) => string?,   // reads the cell value
 *     format:    'text'|'number'|'contact-text', // optional cell hint
 *   }
 *
 * Where the spec omits a getter, the row is expected to expose a
 * value at row[key] directly (escape hatch for flat rows).
 *
 * Low-level IO (downloadCsv, openPdfPrintWindow) is re-used from
 * the Guest Log analytics module — one source of truth for the
 * anchor-download and new-window-print plumbing.
 *
 * Cover-page rendering lives here (not in guestLogAnalytics) so
 * future modules have a single owner to extend. Guest Log's PDF
 * already renders its own inline cover; it continues to do so
 * (no behavioural change in Module 5).
 */

import { downloadCsv, openPdfPrintWindow } from './guestLogAnalytics';
import { formatDateTime } from './appointmentState';

export { downloadCsv, openPdfPrintWindow };

/* ── HTML-escape — local copy so this file has zero cross-module
   dependency on guestLog internals beyond the two IO helpers. */
export function escapeHtml(s) {
  if (s == null) return '';
  return String(s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

/* ── CSV ─────────────────────────────────────────────────────── */

function csvQuote(value) {
  if (value == null) return '""';
  const s = String(value);
  return `"${s.replace(/"/g, '""')}"`;
}

function csvContactExcelGuard(value) {
  if (!value) return '""';
  /* Excel-safe text prefix so +91 / +971 don't get re-parsed as
     numbers. */
  return `=${csvQuote(value)}`;
}

function readCell(row, col, ctx) {
  try {
    const val = typeof col.getter === 'function'
      ? col.getter(row, ctx)
      : row?.[col.key];
    return val == null ? '' : val;
  } catch { return ''; }
}

/**
 * buildCsvFromSpec — UTF-8 BOM + RFC 4180 + \r\n.
 *
 *   buildCsvFromSpec(rows, columns, { ctx })
 */
export function buildCsvFromSpec(rows, columns, options = {}) {
  const ctx = options.ctx || {};
  const bom = '\uFEFF';
  const header = columns.map((c) => csvQuote(c.label)).join(',');
  const body = (rows || []).map((row, idx) => {
    const cells = columns.map((c) => {
      const raw = c.key === '__sr' ? String(idx + 1) : readCell(row, c, ctx);
      if (c.format === 'contact-text') return csvContactExcelGuard(raw);
      return csvQuote(raw);
    });
    return cells.join(',');
  }).join('\r\n');
  return `${bom}${header}\r\n${body}${body ? '\r\n' : ''}`;
}

/* ── PDF cover page + table ─────────────────────────────────── */

/**
 * buildCoverPageHtml — standalone cover page used by report PDFs.
 *
 *   buildCoverPageHtml({
 *     orgName, title, subtitle, filterSummary, rowCount,
 *     generatedBy, generatedAtIso,
 *   })
 */
export function buildCoverPageHtml({
  orgName = 'CorpGMS',
  title = 'Report',
  subtitle = '',
  filterSummary = '',
  rowCount = 0,
  generatedBy = '—',
  generatedAtIso = null,
} = {}) {
  const genAt = generatedAtIso
    ? formatDateTime(generatedAtIso)
    : formatDateTime(new Date().toISOString());
  return `
    <div class="cover">
      <div style="border-bottom: 3px solid #0284C7; padding-bottom: 12pt; margin-bottom: 16pt;">
        <div style="font-family: 'Outfit', Arial, sans-serif; font-weight: 800; font-size: 14pt; color: #0284C7;">
          ${escapeHtml(orgName)}
        </div>
      </div>
      <h1>${escapeHtml(title)}</h1>
      ${subtitle ? `<h2>${escapeHtml(subtitle)}</h2>` : ''}
      <h2>${escapeHtml(Number(rowCount).toLocaleString('en-GB'))} record${rowCount === 1 ? '' : 's'}</h2>
      <div class="meta">
        ${filterSummary ? `<div><span class="label">Filter summary:</span>${escapeHtml(filterSummary)}</div>` : ''}
        <div><span class="label">Generated by:</span>${escapeHtml(generatedBy)}</div>
        <div><span class="label">Generated at:</span>${escapeHtml(genAt)}</div>
      </div>
    </div>
  `;
}

/**
 * buildPdfHtmlFromSpec — full HTML document (A4 landscape) with
 * cover page + table. Columns drive header row + body cell layout.
 *
 * options:
 *   orgName, title, subtitle, filterSummary, generatedBy,
 *   generatedAtIso, pageOrientation ('landscape' | 'portrait'),
 *   ctx (passed to getters), extraSectionsHtml (injected after cover).
 */
export function buildPdfHtmlFromSpec(rows, columns, options = {}) {
  const {
    orgName = 'CorpGMS',
    title = 'Report',
    subtitle = '',
    filterSummary = '',
    generatedBy = '—',
    generatedAtIso = null,
    pageOrientation = 'landscape',
    ctx = {},
    extraSectionsHtml = '',
  } = options;

  const headerRow = columns
    .map((c) => `<th style="${c.width ? `width:${c.width};` : ''}text-align:left;padding:4px 6px;border-bottom:2px solid #0C2340;font-size:9pt;">${escapeHtml(c.label)}</th>`)
    .join('');

  const bodyRows = (rows || []).map((row, idx) => {
    const cells = columns.map((c) => {
      const val = c.key === '__sr' ? String(idx + 1) : readCell(row, c, ctx);
      const alignStyle = c.format === 'number' ? 'text-align:right;' : '';
      /* Allow the getter to return HTML for status-pill rendering.
         A getter whose key ends with ':html' or returns a value with
         the __html sentinel will be injected un-escaped. */
      const raw = val && typeof val === 'object' && '__html' in val
        ? String(val.__html || '')
        : escapeHtml(val);
      return `<td style="padding:4px 6px;border-bottom:1px solid #E5E7EB;font-size:9pt;${alignStyle}">${raw}</td>`;
    }).join('');
    return `<tr style="page-break-inside:avoid;">${cells}</tr>`;
  }).join('');

  const cover = buildCoverPageHtml({
    orgName, title, subtitle, filterSummary,
    rowCount: (rows || []).length,
    generatedBy, generatedAtIso,
  });

  const footer = escapeHtml(`${title} · ${orgName}`);
  const genAt = generatedAtIso
    ? formatDateTime(generatedAtIso)
    : formatDateTime(new Date().toISOString());

  return `<!doctype html>
<html lang="en-GB">
  <head>
    <meta charset="utf-8" />
    <title>${escapeHtml(title)} — ${escapeHtml(orgName)}</title>
    <style>
      @page { size: A4 ${pageOrientation}; margin: 15mm; }
      html, body { margin: 0; padding: 0; color: #0C2340; font-family: 'Plus Jakarta Sans', Arial, sans-serif; }
      .cover { page-break-after: always; padding: 20mm 10mm; }
      .cover h1 { font-family: 'Outfit', Arial, sans-serif; font-size: 28pt; margin: 0 0 4pt 0; }
      .cover h2 { font-size: 14pt; margin: 6pt 0 6pt 0; color: #6B7280; font-weight: 600; }
      .cover .meta { font-size: 10pt; line-height: 1.7; color: #374151; }
      .cover .meta .label { color: #6B7280; display: inline-block; min-width: 140px; }
      table { width: 100%; border-collapse: collapse; }
      thead { display: table-header-group; }
      tr { page-break-inside: avoid; }
      .footer {
        position: fixed; bottom: 8mm; left: 15mm; right: 15mm;
        font-size: 8pt; color: #6B7280;
        display: flex; justify-content: space-between;
      }
    </style>
  </head>
  <body>
    ${cover}
    ${extraSectionsHtml || ''}
    <table>
      <thead>
        <tr style="background:#E0F2FE;">${headerRow}</tr>
      </thead>
      <tbody>
        ${bodyRows || `<tr><td colspan="${columns.length}" style="padding:20pt;text-align:center;color:#6B7280;font-size:10pt;">No records found.</td></tr>`}
      </tbody>
    </table>
    <div class="footer">
      <div>${footer}</div>
      <div>${escapeHtml(genAt)}</div>
    </div>
    <script>
      window.addEventListener('load', function() {
        window.focus();
        setTimeout(function() { window.print(); }, 250);
      });
      window.addEventListener('afterprint', function() { window.close(); });
    </script>
  </body>
</html>`;
}

/**
 * Render a status-pill span with inline colour for PDF embedding.
 * Exposed so report builders can stamp coloured status cells.
 */
export function pdfStatusPill(label, color = '#6B7280') {
  return {
    __html: `<span style="display:inline-block;padding:1px 6px;border-radius:10px;font-weight:700;background:${color}22;color:${color};">${escapeHtml(label)}</span>`,
  };
}
